name: "docs-devel try docs on GitHub Pages"
 
on:
  workflow_dispatch:

jobs:
 
  build-and-try-docs:

    runs-on: ubuntu-20.04
    container: ubuntu:20.04
 
    steps:
 
    - name: "Before"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: "Build on gh-pages for versions (devel.sh)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/_cicd/devel.sh"
      shell: bash
