name: docs_deploy
 
on:
  workflow_dispatch:

jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: ubuntu:latest
 
    steps:
 
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: Build devel documentation and update GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/_cicd/cicd.sh devel"
      shell: bash
