name: "docs-deploy (toulbar2 site on GitHub Pages)"

# workflow automatically executed when push to master
# + workflow_dispatch (manual)
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'master'

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: 'sphinx-nr'

      #- name: "Cache"
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/.cache/pip
      #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pip-

      # Install

      - name: "Doxygen install"
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake g++ libgmp-dev libboost-graph-dev libboost-iostreams-dev zlib1g-dev liblzma-dev libxml2-dev libopenmpi-dev libboost-mpi-dev libjemalloc-dev pkg-config texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk graphviz doxygen
        shell: bash

      - name: "Python setup"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "Sphinx install"
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/_local/requirement.txt

      # Build

      - name: "Doxygen build"
        run: |
          mkdir build
          cd build
          cmake -DBUILD_API_DOC=ON ..
          make doc

      - name: "Sphinx build"
        run: |
          cd docs
          make docs

      # Deploy on Github Pages

      - name: "Run ghp-import"
        run: | 
          ghp-import -n -p -f docs/_build/html

      # Runs a set of commands using the runners shell
      - name: "Run a multi-line script"
        run: |
          echo "Add other actions to build...?"

